name: Executar Imagem Docker

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar e Executar Imagem
      run: |
        docker pull ghcr.io/tushingataforz/meu-app:latest
        docker run --rm ghcr.io/tushingataforz/meu-app:latest
